# Namespace where app will run
namespace: airline

# Docker image (Jenkins update ചെയ്യും)
image:
  repository: 899805259415.dkr.ecr.ap-south-1.amazonaws.com/airline-backend
  tag: "9"

# Number of pods
replicaCount: 2

# Service config
service:
  port: 5000

# Public domain
ingress:
  host: api.techianadict.online
  certificateArn: arn:aws:acm:ap-south-1:899805259415:certificate/cfdb1f61-6b49-4fdc-b782-d609d3c00520

# Non-sensitive config
config:
  NODE_ENV: production
  DB_HOST: airline-platform-postgres.ctqs0e4ucayc.ap-south-1.rds.amazonaws.com
  DB_NAME: airline_db
  DB_PORT: "5432"

# Sensitive config
secret:
  DB_USER: postgres
  DB_PASSWORD: password123


