# Secret = sensitive data (passwords)
apiVersion: v1
kind: Secret

metadata:
  name: airline-backend-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  DB_USER: {{ .Values.secret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}